Diminish the number of params being logged
Possible cause of:

pymongo.errors.WriteError: Resulting document after update is larger
than 16777216, full error: {'index': 0, 'code': 17419, 'errmsg':
'Resulting document after update is larger than 16777216'}